api_platform:
    title: Event Booking API
    version: 1.0.0
    show_webby: false
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    path_segment_name_generator: api_platform.metadata.path_segment_name_generator.dash
    formats:
        jsonld: [ "application/ld+json" ]
        json: [ "application/json" ]
